server:
  port: 8080

spring:
  application:
    name: url-shortener-api

  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "dmVyeS1zZWNyZXQta2V5LXZlcnktc2VjcmV0LWtleS12ZXJ5LXNlY3JldC1rZXk="
  expiration: 86400000

app:
  base-url: http://localhost:8080